### ISSUE TITLE
custom setting vnp_SecureHashType 

### ISSUE THREAD

**Issue by nguyentiengiang** [phpviet/omnipay-vnpay#1]
Hi bạn,
Cảm ơn vì đã viết thư viện hỗ trợ cho VNPay.
Mình đã sử dụng trên môi trường sandbox và thấy setting `vnp_SecureHashType` bằng **md5** không hoạt động.
Hy vọng có thể custom để sử dụng được loại hash type khác.

**Comment by vuongxuongminh** [comment]
Đã hổ trợ, bạn check lại nhé https://github.com/phpviet/omnipay-vnpay/releases/tag/1.0.1

**Comment by nguyentiengiang** [comment]
thanks bạn
